[2022-03-14 00:18:41,716] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-03-14T00:18:41.089653+00:00 [queued]>
[2022-03-14 00:18:41,729] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-03-14T00:18:41.089653+00:00 [queued]>
[2022-03-14 00:18:41,730] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 00:18:41,731] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-14 00:18:41,731] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 00:18:41,743] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2022-03-14 00:18:41.089653+00:00
[2022-03-14 00:18:41,748] {standard_task_runner.py:52} INFO - Started process 195 to run task
[2022-03-14 00:18:41,753] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', 'manual__2022-03-14T00:18:41.089653+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmpafxthn6m', '--error-file', '/tmp/tmpno0h16wi']
[2022-03-14 00:18:41,754] {standard_task_runner.py:77} INFO - Job 5: Subtask load_seed_data_once
[2022-03-14 00:18:41,813] {logging_mixin.py:109} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-03-14T00:18:41.089653+00:00 [running]> on host 1910aafd392e
[2022-03-14 00:18:41,912] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_init_once_seed_data
AIRFLOW_CTX_TASK_ID=load_seed_data_once
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T00:18:41.089653+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-14T00:18:41.089653+00:00
[2022-03-14 00:18:41,914] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-14 00:18:41,916] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /dbt && dbt seed --profiles-dir .']
[2022-03-14 00:18:41,929] {subprocess.py:85} INFO - Output:
[2022-03-14 00:18:44,940] {subprocess.py:89} INFO - Running with dbt=0.20.0
[2022-03-14 00:18:49,253] {subprocess.py:89} INFO - Found 5 models, 0 tests, 0 snapshots, 0 analyses, 338 macros, 0 operations, 3 seed files, 0 sources, 0 exposures
[2022-03-14 00:18:49,255] {subprocess.py:89} INFO - 
[2022-03-14 00:18:51,540] {subprocess.py:89} INFO - 00:18:51 | Concurrency: 200 threads (target='dev')
[2022-03-14 00:18:51,541] {subprocess.py:89} INFO - 00:18:51 |
[2022-03-14 00:18:51,581] {subprocess.py:89} INFO - 00:18:51 | 1 of 3 START seed file public.bookings_1............................. [RUN]
[2022-03-14 00:18:51,583] {subprocess.py:89} INFO - 00:18:51 | 2 of 3 START seed file public.bookings_2............................. [RUN]
[2022-03-14 00:18:51,584] {subprocess.py:89} INFO - 00:18:51 | 3 of 3 START seed file public.customers.............................. [RUN]
[2022-03-14 00:18:52,366] {subprocess.py:89} INFO - * Deprecation Warning: The quote_columns parameter was not set for seeds, so the
[2022-03-14 00:18:52,367] {subprocess.py:89} INFO - default value of False was chosen. The default will change to True in a future
[2022-03-14 00:18:52,368] {subprocess.py:89} INFO - release.
[2022-03-14 00:18:52,368] {subprocess.py:89} INFO - 
[2022-03-14 00:18:52,369] {subprocess.py:89} INFO - For more information, see:
[2022-03-14 00:18:52,369] {subprocess.py:89} INFO - https://docs.getdbt.com/v0.15/docs/seeds#section-specify-column-quoting
[2022-03-14 00:18:53,893] {subprocess.py:89} INFO - 00:18:53 | 3 of 3 OK loaded seed file public.customers.......................... [[32mINSERT 2[0m in 2.30s]
[2022-03-14 00:18:53,895] {subprocess.py:89} INFO - 00:18:53 | 2 of 3 OK loaded seed file public.bookings_2......................... [[32mINSERT 7[0m in 2.30s]
[2022-03-14 00:18:53,896] {subprocess.py:89} INFO - 00:18:53 | 1 of 3 OK loaded seed file public.bookings_1......................... [[32mINSERT 7[0m in 2.31s]
[2022-03-14 00:18:54,428] {subprocess.py:89} INFO - 00:18:54 |
[2022-03-14 00:18:54,429] {subprocess.py:89} INFO - 00:18:54 | Finished running 3 seeds in 5.17s.
[2022-03-14 00:18:54,449] {subprocess.py:89} INFO - 
[2022-03-14 00:18:54,451] {subprocess.py:89} INFO - [32mCompleted successfully[0m
[2022-03-14 00:18:54,452] {subprocess.py:89} INFO - 
[2022-03-14 00:18:54,452] {subprocess.py:89} INFO - Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2022-03-14 00:18:55,785] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-14 00:18:55,811] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20220314T001841, start_date=20220314T001841, end_date=20220314T001855
[2022-03-14 00:18:55,863] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-14 00:18:55,893] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
