[2022-04-03 23:02:31,568] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-04-03T23:02:30.023567+00:00 [queued]>
[2022-04-03 23:02:31,588] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-04-03T23:02:30.023567+00:00 [queued]>
[2022-04-03 23:02:31,589] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-03 23:02:31,591] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-04-03 23:02:31,591] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-03 23:02:31,616] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2022-04-03 23:02:30.023567+00:00
[2022-04-03 23:02:31,626] {standard_task_runner.py:52} INFO - Started process 312 to run task
[2022-04-03 23:02:31,640] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', 'manual__2022-04-03T23:02:30.023567+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmpbsp4bov7', '--error-file', '/tmp/tmppi1bzmds']
[2022-04-03 23:02:31,641] {standard_task_runner.py:77} INFO - Job 62: Subtask load_seed_data_once
[2022-04-03 23:02:31,766] {logging_mixin.py:109} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-04-03T23:02:30.023567+00:00 [running]> on host b1d7081b9a1b
[2022-04-03 23:02:31,928] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_init_once_seed_data
AIRFLOW_CTX_TASK_ID=load_seed_data_once
AIRFLOW_CTX_EXECUTION_DATE=2022-04-03T23:02:30.023567+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-03T23:02:30.023567+00:00
[2022-04-03 23:02:31,930] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-03 23:02:31,932] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /dbt && dbt seed --profiles-dir .']
[2022-04-03 23:02:31,949] {subprocess.py:85} INFO - Output:
[2022-04-03 23:02:36,360] {subprocess.py:89} INFO - 23:02:36  Running with dbt=1.0.0
[2022-04-03 23:02:37,081] {subprocess.py:89} INFO - 23:02:37  Found 5 models, 2 tests, 0 snapshots, 0 analyses, 581 macros, 0 operations, 3 seed files, 0 sources, 0 exposures, 0 metrics
[2022-04-03 23:02:37,084] {subprocess.py:89} INFO - 23:02:37
[2022-04-03 23:02:38,917] {subprocess.py:89} INFO - 23:02:38  Concurrency: 200 threads (target='dev')
[2022-04-03 23:02:38,919] {subprocess.py:89} INFO - 23:02:38
[2022-04-03 23:02:39,130] {subprocess.py:89} INFO - 23:02:39  1 of 3 START seed file public.bookings_1........................................ [RUN]
[2022-04-03 23:02:39,133] {subprocess.py:89} INFO - 23:02:39  2 of 3 START seed file public.bookings_2........................................ [RUN]
[2022-04-03 23:02:39,135] {subprocess.py:89} INFO - 23:02:39  3 of 3 START seed file public.customers......................................... [RUN]
[2022-04-03 23:02:42,037] {subprocess.py:89} INFO - 23:02:42  2 of 3 OK loaded seed file public.bookings_2.................................... [INSERT 7 in 2.90s]
[2022-04-03 23:02:42,048] {subprocess.py:89} INFO - 23:02:42  1 of 3 OK loaded seed file public.bookings_1.................................... [INSERT 7 in 2.91s]
[2022-04-03 23:02:42,208] {subprocess.py:89} INFO - 23:02:42  3 of 3 OK loaded seed file public.customers..................................... [INSERT 2 in 3.07s]
[2022-04-03 23:02:42,290] {subprocess.py:89} INFO - 23:02:42
[2022-04-03 23:02:42,292] {subprocess.py:89} INFO - 23:02:42  Finished running 3 seeds in 5.20s.
[2022-04-03 23:02:42,333] {subprocess.py:89} INFO - 23:02:42
[2022-04-03 23:02:42,336] {subprocess.py:89} INFO - 23:02:42  Completed successfully
[2022-04-03 23:02:42,337] {subprocess.py:89} INFO - 23:02:42
[2022-04-03 23:02:42,339] {subprocess.py:89} INFO - 23:02:42  Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2022-04-03 23:02:43,648] {subprocess.py:93} INFO - Command exited with return code 0
[2022-04-03 23:02:43,671] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20220403T230230, start_date=20220403T230231, end_date=20220403T230243
[2022-04-03 23:02:43,705] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-03 23:02:43,729] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
