[2022-03-16 02:33:01,785] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 2_daily_transformation_analysis.daily_transform manual__2022-03-16T02:33:00.937558+00:00 [queued]>
[2022-03-16 02:33:01,799] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 2_daily_transformation_analysis.daily_transform manual__2022-03-16T02:33:00.937558+00:00 [queued]>
[2022-03-16 02:33:01,800] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 02:33:01,801] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-16 02:33:01,802] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 02:33:01,817] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): daily_transform> on 2022-03-16 02:33:00.937558+00:00
[2022-03-16 02:33:01,822] {standard_task_runner.py:52} INFO - Started process 354 to run task
[2022-03-16 02:33:01,828] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', '2_daily_transformation_analysis', 'daily_transform', 'manual__2022-03-16T02:33:00.937558+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/transform_and_analysis.py', '--cfg-path', '/tmp/tmplkdr0av0', '--error-file', '/tmp/tmpdrmklpko']
[2022-03-16 02:33:01,829] {standard_task_runner.py:77} INFO - Job 42: Subtask daily_transform
[2022-03-16 02:33:01,896] {logging_mixin.py:109} INFO - Running <TaskInstance: 2_daily_transformation_analysis.daily_transform manual__2022-03-16T02:33:00.937558+00:00 [running]> on host 812778d1d7d0
[2022-03-16 02:33:02,016] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=2_daily_transformation_analysis
AIRFLOW_CTX_TASK_ID=daily_transform
AIRFLOW_CTX_EXECUTION_DATE=2022-03-16T02:33:00.937558+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-16T02:33:00.937558+00:00
[2022-03-16 02:33:02,018] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-16 02:33:02,021] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /dbt && dbt run --models transform --profiles-dir .']
[2022-03-16 02:33:02,040] {subprocess.py:85} INFO - Output:
[2022-03-16 02:33:06,170] {subprocess.py:89} INFO - 02:33:06  Running with dbt=1.0.0
[2022-03-16 02:33:06,769] {subprocess.py:89} INFO - 02:33:06  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2022-03-16 02:33:06,769] {subprocess.py:89} INFO - There are 2 unused configuration paths:
[2022-03-16 02:33:06,770] {subprocess.py:89} INFO - - models.my_new_project.analysis
[2022-03-16 02:33:06,770] {subprocess.py:89} INFO - - models.my_new_project.transform
[2022-03-16 02:33:06,771] {subprocess.py:89} INFO - 
[2022-03-16 02:33:06,807] {subprocess.py:89} INFO - 02:33:06  Found 2 models, 4 tests, 0 snapshots, 0 analyses, 579 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
[2022-03-16 02:33:06,808] {subprocess.py:89} INFO - 02:33:06  The selection criterion 'transform' does not match any nodes
[2022-03-16 02:33:06,810] {subprocess.py:89} INFO - 02:33:06
[2022-03-16 02:33:06,812] {subprocess.py:89} INFO - 02:33:06  [WARNING]: Nothing to do. Try checking your model configs and model specification args
[2022-03-16 02:33:08,263] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-16 02:33:08,289] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=2_daily_transformation_analysis, task_id=daily_transform, execution_date=20220316T023300, start_date=20220316T023301, end_date=20220316T023308
[2022-03-16 02:33:08,324] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-16 02:33:08,360] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
