[2022-03-16 02:33:08,654] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 2_daily_transformation_analysis.daily_analysis manual__2022-03-16T02:33:00.937558+00:00 [queued]>
[2022-03-16 02:33:08,665] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 2_daily_transformation_analysis.daily_analysis manual__2022-03-16T02:33:00.937558+00:00 [queued]>
[2022-03-16 02:33:08,665] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 02:33:08,666] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-16 02:33:08,666] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 02:33:08,676] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): daily_analysis> on 2022-03-16 02:33:00.937558+00:00
[2022-03-16 02:33:08,681] {standard_task_runner.py:52} INFO - Started process 367 to run task
[2022-03-16 02:33:08,684] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', '2_daily_transformation_analysis', 'daily_analysis', 'manual__2022-03-16T02:33:00.937558+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/transform_and_analysis.py', '--cfg-path', '/tmp/tmpnxwo05cw', '--error-file', '/tmp/tmpnweqwi44']
[2022-03-16 02:33:08,685] {standard_task_runner.py:77} INFO - Job 43: Subtask daily_analysis
[2022-03-16 02:33:08,738] {logging_mixin.py:109} INFO - Running <TaskInstance: 2_daily_transformation_analysis.daily_analysis manual__2022-03-16T02:33:00.937558+00:00 [running]> on host 812778d1d7d0
[2022-03-16 02:33:08,815] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=2_daily_transformation_analysis
AIRFLOW_CTX_TASK_ID=daily_analysis
AIRFLOW_CTX_EXECUTION_DATE=2022-03-16T02:33:00.937558+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-16T02:33:00.937558+00:00
[2022-03-16 02:33:08,816] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-16 02:33:08,817] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /dbt && dbt run --models analysis --profiles-dir .']
[2022-03-16 02:33:08,827] {subprocess.py:85} INFO - Output:
[2022-03-16 02:33:12,264] {subprocess.py:89} INFO - 02:33:12  Running with dbt=1.0.0
[2022-03-16 02:33:12,540] {subprocess.py:89} INFO - 02:33:12  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2022-03-16 02:33:12,540] {subprocess.py:89} INFO - There are 2 unused configuration paths:
[2022-03-16 02:33:12,541] {subprocess.py:89} INFO - - models.my_new_project.transform
[2022-03-16 02:33:12,541] {subprocess.py:89} INFO - - models.my_new_project.analysis
[2022-03-16 02:33:12,542] {subprocess.py:89} INFO - 
[2022-03-16 02:33:12,578] {subprocess.py:89} INFO - 02:33:12  Found 2 models, 4 tests, 0 snapshots, 0 analyses, 579 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
[2022-03-16 02:33:12,580] {subprocess.py:89} INFO - 02:33:12  The selection criterion 'analysis' does not match any nodes
[2022-03-16 02:33:12,583] {subprocess.py:89} INFO - 02:33:12
[2022-03-16 02:33:12,585] {subprocess.py:89} INFO - 02:33:12  [WARNING]: Nothing to do. Try checking your model configs and model specification args
[2022-03-16 02:33:13,963] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-16 02:33:13,989] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=2_daily_transformation_analysis, task_id=daily_analysis, execution_date=20220316T023300, start_date=20220316T023308, end_date=20220316T023313
[2022-03-16 02:33:14,014] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-16 02:33:14,052] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
